name: Build APKs

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/build/outputs/apk/debug/android-debug.apk
